<?xml version="1.0" encoding="utf-8"?><Database Name="ArtileriManagement" Class="ManagementDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=ArtileriManagement;Integrated Security=True" SettingsObjectName="SharpArtileri.Data.Properties.Settings" SettingsPropertyName="ArtileriManagementConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Company" Member="Companies">
    <Type Name="Company">
      <Column Name="Code" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="POApproverName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ConnectionString" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>